---
- name: Configure customer port on undefined
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - netbox.netbox

  tasks:
    - name: Configure port in NetBox
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ $env.NETBOX_URL }}            # mandatory
        netbox_token: "${netboxToken}"        # mandatory
        validate_certs: false
        data:
          device: "undefined"           # mandatory
          name: "Port 4"    # mandatory
          type: "1000base-t"                   # mandatory for creation
          enabled: true
          mtu: 1500
          mac_address: "00:11:22:33:44:55"
          mode: null
          mgmt_only: false
          untagged_vlan: null
          tagged_vlans: []
          lag: null
          description: "Customer port on undefined"
          custom_fields: {}
          tags: []
        state: present                        # mandatory
